name: everactive-nats
version: 2.1.9
summary: A simple, secure and high performance open source messaging system
description: |
  NATS.io is a simple, secure and high performance open source messaging system for cloud
  native applications, IoT messaging, and microservices architectures.
confinement: strict
grade: stable

apps:
  server:
    command: bin/start-nats.sh
    daemon: simple
    plugs: [network-bind]

  configure:
    command: bin/run-configure

  get-configuration:
    command: bin/run-get-configuration

hooks:
  configure:
    plugs: [network]

parts:
  nats:
    plugin: go
    go-importpath: github.com/nats-io/nats-server/v2
    source: https://github.com/nats-io/nats-server
    source-tag: v2.1.9
    source-type: git
    build-snaps:
    # Upstream still builds their releases with 1.14
    - go/1.14/stable
    override-build: |
      unset GOPATH
      export GO111MODULE=on
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/bin
      go build -mod vendor -o nats-server
      cp nats-server "$SNAPCRAFT_PART_INSTALL"/bin
    stage:
    - bin/nats-server

  scripts:
    plugin: dump
    source: scripts
    organize:
      start-nats.sh: bin/start-nats.sh
      'run-*': bin/
    stage:
    - bin/*
